### ISSUE TITLE
Check that the package is not installed

### ISSUE THREAD

**Issue by frenzymadness** [mmerickel/pytest-venv#3]
Hi.

We use `get_version` to check if a package is installed and in which specific version. However, if I want to check that some package is intentionally missing, `get_version` is not useful because if a package does not exist, it raises `subprocess.CalledProcessError`.

I think that it might be better to return `None` if a package is not present in a virtual environment. Or we might create a new method for this, something like `get_version_or_none` to keep the API stable.

What do you think?

**Comment by mmerickel** [comment]
Implemented in #7.
